#!/bin/bash

set -e

PROJECT_DIR=$(pwd)
PROJECT_NAME=$1

if [ -z "$PROJECT_NAME" ]; then
  echo "Usage: $0 <project_name>"
  exit 1
fi

REPO_URL="https://github.com/srijanss/ansible-scaffold"
TMP_DIR=$(mktemp -d)
ANSIBLE_SCAFFOLD_DIR="$TMP_DIR/ansible-scaffold"
git clone $REPO_URL $ANSIBLE_SCAFFOLD_DIR

cd $ANSIBLE_SCAFFOLD_DIR
echo "Creating Ansible scaffold in: $PROJECT_DIR/$PROJECT_NAME"
ansible-playbook create_ansible_playbook.yaml -e ansible_dir="$PROJECT_NAME" 
cp -r $PROJECT_NAME "$PROJECT_DIR"
rm -rf $TMP_DIR 
echo "Ansible scaffold created successfully in: $PROJECT_DIR/$PROJECT_NAME"