- name: Create ansible playbook
  hosts: localhost
  vars:
    ansible_dir: "ansible-playbook"
    app_name: "my-app"

  tasks:
    - name: Create ansible directory
      file:
        path: "{{ ansible_dir }}"
        state: directory

    - name: Create group_vars directories
      file:
        path: "{{ ansible_dir }}/group_vars"
        state: directory

    - name: Create staging.yaml inside group_vars
      template:
        src: templates/group_vars/staging.yaml.j2
        dest: "{{ ansible_dir }}/group_vars/staging.yaml"

    - name: Create inventories directories
      file:
        path: "{{ ansible_dir }}/inventories/{{ item }}"
        state: directory
        recurse: yes
      loop:
        - staging
        - production

    - name: Create staging hosts.yaml file inside inventories
      template:
        src: templates/inventories/staging/hosts.yaml.j2
        dest: "{{ ansible_dir }}/inventories/staging/hosts.yaml"

    - name: Create production hosts.yaml file inside inventories
      template:
        src: templates/inventories/production/hosts.yaml.j2
        dest: "{{ ansible_dir }}/inventories/production/hosts.yaml"

    - name: Create roles directories
      file:
        path: "{{ ansible_dir }}/{{ item }}"
        state: directory
        recurse: yes
      loop:
        - roles/build/tasks
        - roles/deploy/tasks
        - roles/deploy/templates

    - name: Create build role
      template:
        src: templates/roles/build/tasks/main.yaml.j2
        dest: "{{ ansible_dir }}/roles/build/tasks/main.yaml"

    - name: Create deploy role
      template:
        src: templates/roles/deploy/tasks/main.yaml.j2
        dest: "{{ ansible_dir }}/roles/deploy/tasks/main.yaml"

    - name: Create deploy role template
      template:
        src: templates/roles/deploy/templates/values.yaml.j2
        dest: "{{ ansible_dir }}/roles/deploy/templates/values.yaml.j2"

    - name: Create build playbook
      template:
        src: templates/build_playbook.yaml.j2
        dest: "{{ ansible_dir }}/build_playbook.yaml"

    - name: Create deploy playbook
      template:
        src: templates/deploy_playbook.yaml.j2
        dest: "{{ ansible_dir }}/deploy_playbook.yaml"

    - name: Create helm charts directories
      file:
        path: "{{ ansible_dir }}/helm_charts/{{ item }}"
        state: directory
        recurse: yes
      loop:
        - "{{ app_name }}"
        - "{{ app_name }}/templates"
        - "{{ app_name }}/templates/tests"

    - name: Create helm Chart.yaml
      template:
        src: templates/helm_charts/Chart.yaml.j2
        dest: "{{ ansible_dir }}/helm_charts/{{ app_name }}/Chart.yaml"

    - name: Create template test-connection.yaml
      template:
        src: templates/helm_charts/templates/tests/test-connection.yaml.j2
        dest: "{{ ansible_dir }}/helm_charts/{{ app_name }}/templates/tests/test-connection.yaml"

    - name: Create _helpers.tpl
      template:
        src: templates/helm_charts/templates/_helpers.tpl.j2
        dest: "{{ ansible_dir }}/helm_charts/{{ app_name }}/templates/_helpers.tpl"
