- name: Create ansible playbook
  hosts: localhost
  vars:
    ansible_dir: "ansible-playbook"
    app_name: "my-app"
    action: "ansible"

  tasks:
    - name: Create ansible directory
      file:
        path: "{{ ansible_dir }}"
        state: directory

    - name: Create group_vars directories
      file:
        path: "{{ ansible_dir }}/group_vars"
        state: directory

    - name: Create staging.yaml inside group_vars
      template:
        src: templates/group_vars/staging.yaml.j2
        dest: "{{ ansible_dir }}/group_vars/staging.yaml"

    - name: Create inventories directories
      file:
        path: "{{ ansible_dir }}/inventories/{{ item }}"
        state: directory
        recurse: yes
      loop:
        - staging
        - production

    - name: Create staging hosts.yaml file inside inventories
      template:
        src: templates/inventories/staging/hosts.yaml.j2
        dest: "{{ ansible_dir }}/inventories/staging/hosts.yaml"

    - name: Create production hosts.yaml file inside inventories
      template:
        src: templates/inventories/production/hosts.yaml.j2
        dest: "{{ ansible_dir }}/inventories/production/hosts.yaml"

    - name: Create roles directories
      file:
        path: "{{ ansible_dir }}/{{ item }}"
        state: directory
        recurse: yes
      loop:
        - roles/build/tasks
        - roles/deploy/tasks
        - roles/deploy/templates

    - name: Create build role
      template:
        src: templates/roles/build/tasks/main.yaml.j2
        dest: "{{ ansible_dir }}/roles/build/tasks/main.yaml"

    - name: Create deploy role
      template:
        src: templates/roles/deploy/tasks/main.yaml.j2
        dest: "{{ ansible_dir }}/roles/deploy/tasks/main.yaml"

    - name: Create deploy role template
      template:
        src: templates/roles/deploy/templates/values.yaml.j2
        dest: "{{ ansible_dir }}/roles/deploy/templates/values.yaml.j2"

    - name: Create build playbook
      template:
        src: templates/build_playbook.yaml.j2
        dest: "{{ ansible_dir }}/build_playbook.yaml"

    - name: Create deploy playbook
      template:
        src: templates/deploy_playbook.yaml.j2
        dest: "{{ ansible_dir }}/deploy_playbook.yaml"

    - name: Create build_and_deploy playbook
      template:
        src: templates/build_and_deploy.yaml.j2
        dest: "{{ ansible_dir }}/build_and_deploy.yaml"

    - name: Create ansible.cfg file
      template:
        src: templates/ansible.cfg.j2
        dest: "{{ ansible_dir }}/ansible.cfg"

    - name: Create helm charts directories
      file:
        path: "{{ ansible_dir }}/helm_charts/{{ item }}"
        state: directory
        recurse: yes
      loop:
        - "{{ app_name }}"
        - "{{ app_name }}/templates"
        - "{{ app_name }}/templates/tests"
      when: action == "helm_charts"

    - name: Create .helmignore
      template:
        src: templates/helm_charts/.helmignore.j2
        dest: "{{ ansible_dir }}/helm_charts/{{ app_name }}/.helmignore"
      when: action == "helm_charts"

    - name: Create helm Chart.yaml
      template:
        src: templates/helm_charts/Chart.yaml.j2
        dest: "{{ ansible_dir }}/helm_charts/{{ app_name }}/Chart.yaml"
      when: action == "helm_charts"

    - name: Create template test-connection.yaml
      template:
        src: templates/helm_charts/templates/tests/test-connection.yaml.j2
        dest: "{{ ansible_dir }}/helm_charts/{{ app_name }}/templates/tests/test-connection.yaml"
      when: action == "helm_charts"

    - name: Create _helpers.tpl
      template:
        src: templates/helm_charts/templates/_helpers.tpl.j2
        dest: "{{ ansible_dir }}/helm_charts/{{ app_name }}/templates/_helpers.tpl"
      when: action == "helm_charts"

    - name: Create NOTES.txt
      template:
        src: templates/helm_charts/templates/NOTES.txt.j2
        dest: "{{ ansible_dir }}/helm_charts/{{ app_name }}/templates/NOTES.txt"
      when: action == "helm_charts"

    - name: Create configmap.yaml
      template:
        src: templates/helm_charts/templates/configmap.yaml.j2
        dest: "{{ ansible_dir }}/helm_charts/{{ app_name }}/templates/configmap.yaml"
      when: action == "helm_charts"

    - name: Create deployment.yaml
      template:
        src: templates/helm_charts/templates/deployment.yaml.j2
        dest: "{{ ansible_dir }}/helm_charts/{{ app_name }}/templates/deployment.yaml"
      when: action == "helm_charts"

    - name: Create ingress.yaml
      template:
        src: templates/helm_charts/templates/ingress.yaml.j2
        dest: "{{ ansible_dir }}/helm_charts/{{ app_name }}/templates/ingress.yaml"
      when: action == "helm_charts"

    - name: Create secretproviderclass.yaml
      template:
        src: templates/helm_charts/templates/secretproviderclass.yaml.j2
        dest: "{{ ansible_dir }}/helm_charts/{{ app_name }}/templates/secretproviderclass.yaml"
      when: action == "helm_charts"

    - name: Create service.yaml
      template:
        src: templates/helm_charts/templates/service.yaml.j2
        dest: "{{ ansible_dir }}/helm_charts/{{ app_name }}/templates/service.yaml"
      when: action == "helm_charts"
